-- Revenue by Product Category
-- Purpose: calculate total revenue generated by each product category

SELECT
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM order_items AS oi
JOIN products AS p
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;